<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<OutputType>WinExe</OutputType>
		<TargetFramework>net8.0-windows</TargetFramework>
		<RootNamespace>EVO_CRAFT_LAUNCHER</RootNamespace>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
		<UseWPF>true</UseWPF>
		<ApplicationIcon>flavicon.ico</ApplicationIcon>
		<FileVersion>1.0</FileVersion>
		<AssemblyVersion>1.0</AssemblyVersion>
		<PublishSingleFile>false</PublishSingleFile>
		<SelfContained>false</SelfContained>
		<RuntimeIdentifier>win-x64</RuntimeIdentifier>
		<IncludeNativeLibrariesForSelfExtract>false</IncludeNativeLibrariesForSelfExtract>
		<IncludeAllContentForSelfExtract>false</IncludeAllContentForSelfExtract>
		<DebugType>none</DebugType>
		<PublishReadyToRun>false</PublishReadyToRun>
		<PublishDir>bin\FINAL_LAUNCHER\</PublishDir>
		<SatelliteResourceLanguages>en-US</SatelliteResourceLanguages>
		<GenerateAssemblyInfo>false</GenerateAssemblyInfo>
	</PropertyGroup>

	<ItemGroup>
		<Compile Remove="EVO CRAFT LAUNCHER\**" />
		<Compile Remove="Updater EvoCraft\**" />
		<EmbeddedResource Remove="EVO CRAFT LAUNCHER\**" />
		<EmbeddedResource Remove="Updater EvoCraft\**" />
		<None Remove="EVO CRAFT LAUNCHER\**" />
		<None Remove="Updater EvoCraft\**" />
		<Page Remove="EVO CRAFT LAUNCHER\**" />
		<Page Remove="Updater EvoCraft\**" />
	</ItemGroup>

	<ItemGroup>
		<None Remove="background.mp4" />
		<None Remove="discord.png" />
		<None Remove="flavicon.ico" />
		<None Remove="flavicon.png" />
		<None Remove="icon.ico" />
		<None Remove="obfuscar.xml" />
		<None Remove="tiktok.png" />
		<None Remove="youtube.png" />
	</ItemGroup>

	<ItemGroup>
		<Content Include="background.mp4">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</Content>
		<EmbeddedResource Include="obfuscar.xml" />
		<Resource Include="flavicon.ico" />
		<Resource Include="discord.png" />
		<Resource Include="icon.ico" />
		<Resource Include="tiktok.png" />
		<Resource Include="youtube.png" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="BCrypt.Net-Next" Version="4.0.3" />
		<PackageReference Include="CmlLib.Core" Version="4.0.6" />
		<PackageReference Include="CmlLib.Core.Auth.Microsoft" Version="3.3.1" />
		<PackageReference Include="CmlLib.Core.Commons" Version="4.0.0" />
		<PackageReference Include="CmlLib.Core.Installer.Forge" Version="1.1.1" />
		<PackageReference Include="DiscordRichPresence" Version="1.6.1.70" />
		<PackageReference Include="MCStatus.NET" Version="1.0.0" />
		<PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
		<PackageReference Include="Obfuscar" Version="2.2.50">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
		<PackageReference Include="System.Management" Version="10.0.1">
			<PrivateAssets>all</PrivateAssets>
		</PackageReference>
	</ItemGroup>
</Project>