<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <RootNamespace>EVO_CRAFT_LAUNCHER</RootNamespace>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <ApplicationIcon>flavicon.ico</ApplicationIcon>
    <FileVersion>1.0</FileVersion>
    <AssemblyVersion>1.0</AssemblyVersion>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="background.mp4" />
    <None Remove="discord.png" />
    <None Remove="flavicon.ico" />
    <None Remove="flavicon.png" />
    <None Remove="icon.ico" />
    <None Remove="tiktok.png" />
    <None Remove="youtube.png" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="background.mp4">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="flavicon.ico" />
    <Resource Include="discord.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Resource>
    <Resource Include="icon.ico">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="tiktok.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Resource>
    <Resource Include="youtube.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Resource>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="CmlLib.Core" Version="4.0.6" />
    <PackageReference Include="CmlLib.Core.Auth.Microsoft" Version="3.3.1" />
    <PackageReference Include="CmlLib.Core.Commons" Version="4.0.0" />
    <PackageReference Include="CmlLib.Core.Installer.Forge" Version="1.1.1" />
    <PackageReference Include="MCStatus.NET" Version="1.0.0" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
    <PackageReference Include="System.Management" Version="10.0.1" />
  </ItemGroup>

</Project>
